apiVersion: batch/v1beta1
kind: Job
metadata:
  name: job-helloworld-task-5min
spec:
  template:
    spec:
      containers:
      - name: helloworld-task-5min
        image: tkgiacr.azurecr.io/helloworldbatchapp:latest
        imagePullPolicy: Always
        args:
        - helloworld
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: LOGGING__IncludeScopes
          value: "false"
        - name: LOGGING__LogLevel__Default
          value: Warning
        - name: LOGGING__LogLevel__Pivotal
          value: Warning
        - name: LOGGING__LogLevel__Steeltoe
          value: Warning
        - name: LOGGING__Console__DisableColors
          value: "false"
      imagePullSecrets:
      - name: azure-acr
      tolerations:
      - key: "windows"
        operator: "Exists"
        effect: "NoSchedule"
      restartPolicy: Never
  backoffLimit: 4